# Site settings
title: Andrew W. Cull
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Problems I've found fun or interesting or just plain ran into enough during programming, data analysis, or video games.
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://awcull.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown

# Highlighter
highlighter: pygments

# Encoding
encoding: utf-8

# Paginate
paginate: 10
paginate_path: "/blog/page:num"

permalink: /:year/:month/:day/:title.html

analytics:
  provider: google
  google: 
      tracking_id: 'UA-51150113-4'